# Generated by Django 4.0.4 on 2024-06-26 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_tmdbfilm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='author',
        ),
        migrations.RemoveField(
            model_name='film',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.tmdbfilm'),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
